In [1]:
#Introduction to CNN--->
#Convolutional Neural Network ---> It is working for Image related Data


In [3]:
#Images --- > Pixels(0-255)---->0Px (Black),255Px (White)--->
#Normalize (0-1)----> 0P x(black), 1px(white)

In [5]:
#Image

In [7]:
import numpy as np

In [9]:
a=np.random.randint(1,50,9).reshape(3,3)
a

array([[31, 18,  3],
       [42, 33, 16],
       [ 4, 47, 28]])

In [11]:
#Regularization term ---> Pooling Layers--->
#MinPooling
#maxPooling
#GlobalAveragePooling

In [13]:
#stride---> gap or step valuetaht is use for matrix choice.
#kernel-->filteration

In [15]:
a

array([[31, 18,  3],
       [42, 33, 16],
       [ 4, 47, 28]])

In [17]:
#2*2 kernel --->stride=1

In [19]:
[26,36,34,24] , [36,27,24,42]
[34,24,42,25] , [24,42,25,18]

([34, 24, 42, 25], [24, 42, 25, 18])

In [21]:
#MaxPooling Layer --->
#[36], [42], [42], [42]
#MinPooling Layer ---->
#[24],[24],[24],[18]
#GlobalAveragePooling Layer--->
#[30] [32.25] [31.25] [27.25]

In [23]:
a = np.random.randint(1,50,16).reshape(4,4)

In [25]:
a

array([[48, 49,  9, 26],
       [49,  7, 26, 42],
       [ 5, 40, 15, 18],
       [17, 25, 36, 23]])

In [27]:
# 2*2 Kernel --- stride=2

In [29]:
[31,14,17,42], [10,32,5,47],
[49,25,34,7], [6,26,30,15]

([49, 25, 34, 7], [6, 26, 30, 15])

In [31]:
#Dense layers ---> it is considered as fully connected layer and in this , output of first 
#will be the output of second layer. it is working as like a pipeline

In [33]:
#Convolutional Layer---> It is considered as partially connected layer and in this
#we will detect specific parts

In [35]:
#Pooling layer---> it is regularization technique for image related data

In [37]:
#Flatten Layer---> It will convert higher dimensional array 1-D array

In [39]:
#Workflow of CNN--->

In [41]:
#Data Ingestion---> Daya Cleaning and Preprocessing---> Model Sequential Architecture
#CNN_1 layer
#Pooling Layer
#CNN_2 layer
#Pooling Layer
#Flatten Layer(it will convert into 1-D)
#Dense Layer(pipeline)
#Model compile
#Model. training
#Model.Prediction
#Model loss, accuracy